using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("SoundFingerprinting.Infrastructure")]
[assembly: AssemblyDescription("Dependency injection via Service Locator in SoundFingerprinting projects.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Sergiu Ciumac")]
[assembly: AssemblyProduct("SoundFingerprinting.Infrastructure")]
[assembly: AssemblyCopyright("Copyright © Sergiu Ciumac 2017")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("d93d0198-0f7f-4b9f-a318-7209915ff1cf")]
[assembly: AssemblyVersion("3.1.2")]
[assembly: AssemblyInformationalVersion("3.1.2")]
[assembly: InternalsVisibleTo("SoundFingerprinting")]
[assembly: InternalsVisibleTo("SoundFingerprinting.Audio.Bass")]
[assembly: InternalsVisibleTo("SoundFingerprinting.Audio.Bass.Tests")]
[assembly: InternalsVisibleTo("SoundFingerprinting.Audio.NAudio")]
[assembly: InternalsVisibleTo("SoundFingerprinting.SoundTools")]
[assembly: InternalsVisibleTo("SoundFingerprinting.SQL")]
[assembly: InternalsVisibleTo("SoundFingerprinting.MongoDb")]
[assembly: InternalsVisibleTo("SoundFingerprinting.MongoDb.Tests")]
[assembly: InternalsVisibleTo("SoundFingerprinting.Solr")]
[assembly: InternalsVisibleTo("SoundFingerprinting.Solr.Tests")]
[assembly: InternalsVisibleTo("SoundFingerprinting.NeuralHasher")]
[assembly: InternalsVisibleTo("SoundFingerprinting.Tests")]