USE FingerprintsDb
GO
SELECT COUNT(*) AS HASH_COUNTS, HashBin FROM HashBinsMinHash GROUP BY HashBin ORDER BY HASH_COUNTS DESC
GO
SELECT REL.FINGER_COUNT, 20 * REL.FINGER_COUNT AS HASH_COUNT FROM (SELECT COUNT(*) AS FINGER_COUNT FROM Fingerprints) AS REL 
GO
SELECT COUNT(*) AS TRACK_COUNT FROM Tracks
GO