USE FingerprintsDb
GO
IF OBJECT_ID('sp_InsertHashBinMinHash','P') IS NOT NULL
	DROP PROCEDURE sp_InsertHashBinMinHash
GO
CREATE PROCEDURE sp_InsertHashBinMinHash
	@HashBin BIGINT,
	@HashTable INT,
	@SubFingerprintId BIGINT
AS
DECLARE @STR_TO_EXECUTE NVARCHAR(2000)
DECLARE @HASH_TABLE VARCHAR(2)
DECLARE @HASH_BIN VARCHAR(20)
DECLARE @SUB_ID VARCHAR(20)
SELECT @HASH_TABLE = CAST (@HashTable AS VARCHAR(2))
SELECT @HASH_BIN = CAST(@HashBin AS VARCHAR(20))
SELECT @SUB_ID = CAST(@SubFingerprintId AS VARCHAR(20))

SELECT @STR_TO_EXECUTE =
	N'INSERT INTO HashTable_' + @HASH_TABLE + N'(HashBin, SubFingerprintId) ' +
	N'VALUES (' + @HASH_BIN + ', ' + @SUB_ID + ')'

EXEC sp_executesql @STR_TO_EXECUTE
GO
