using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// version and descriptive attributes are generated by the SDK from src/Directory.Build.props and the project file
[assembly: ComVisible(false)]
[assembly: Guid("585f314e-cdad-4c85-a00f-cb4821d158ac")]
[assembly: InternalsVisibleTo("SoundFingerprinting.Tests")]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
[assembly: InternalsVisibleTo("SoundFingerprinting.SoundTools")]
[assembly: InternalsVisibleTo("SoundFingerprinting.NeuralHasher")]
[assembly: InternalsVisibleTo("SoundFingerprinting.FFT.FFTW")]
[assembly: InternalsVisibleTo("SoundFingerprinting.FFT.FFTW.Tests")]
