using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("SoundFingerprinting")]
[assembly: AssemblyDescription("SoundFingerprinting is a C# framework that implements an efficient algorithm of audio identification. Designed for developers, enthusiasts, researchers in the fields of audio processing, data mining, digital signal processing.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Sergiu Ciumac")]
[assembly: AssemblyProduct("SoundFingerprinting Library")]
[assembly: AssemblyCopyright("Copyright © Sergiu Ciumac 2017")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("585f314e-cdad-4c85-a00f-cb4821d158ac")]
[assembly: InternalsVisibleTo("SoundFingerprinting.Tests")]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
[assembly: InternalsVisibleTo("SoundFingerprinting.Audio.NAudio")]
[assembly: InternalsVisibleTo("SoundFingerprinting.Audio.Bass")]
[assembly: InternalsVisibleTo("SoundFingerprinting.Audio.Bass.Tests")]
[assembly: InternalsVisibleTo("SoundFingerprinting.MongoDb")]
[assembly: InternalsVisibleTo("SoundFingerprinting.MongoDb.Tests")]
[assembly: InternalsVisibleTo("SoundFingerprinting.SQL")]
[assembly: InternalsVisibleTo("SoundFingerprinting.SQL.Tests")]
[assembly: InternalsVisibleTo("SoundFingerprinting.Solr")]
[assembly: InternalsVisibleTo("SoundFingerprinting.Solr.Tests")]
[assembly: InternalsVisibleTo("SoundFingerprinting.SoundTools")]
[assembly: InternalsVisibleTo("SoundFingerprinting.NeuralHasher")]
[assembly: InternalsVisibleTo("SoundFingerprinting.FFT.FFTW")]
[assembly: InternalsVisibleTo("SoundFingerprinting.FFT.FFTW.Tests")]
[assembly: InternalsVisibleTo("SoundFingerprinting.DuplicatesDetector")]
[assembly: InternalsVisibleTo("AdDetectionTests")]
[assembly: InternalsVisibleTo("HashCreationFromLocalProfiles")]
[assembly: InternalsVisibleTo("CrompAudioFingerprinting")]
[assembly: InternalsVisibleTo("CrompAudioFingerprintingMaster")]

[assembly: AssemblyVersion("4.1.0")]
[assembly: AssemblyInformationalVersion("4.1.0-alpha")]
