# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

#tokens are generated using the following strategy
#python -c 'print [str(((2**64 / number_of_tokens) * i) - 2**63) for i in range(number_of_tokens)]'

node1ip = '10.11.12.13'
node2ip = '10.11.12.14'
node3ip = '10.11.12.15'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  config.vm.define "cassandra-node-1" do |configNode|
    configNode.vm.hostname = "cassandra-node-1"
    configNode.vm.box = "centos64-x64"
    configNode.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box" 
    configNode.vm.network 'private_network', ip: node1ip
    configNode.vm.network 'public_network'
    
    configNode.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    configNode.vm.provision :chef_solo do |chef|
         chef.log_level = :debug
         chef.json = {
           :cassandra => {
              :repository_username => '<enter username>',
              :repository_password => '<enter password>',
              :cluster_name => 'SoundFingerprinting Cluster',
              :initial_token => '-9223372036854775808',
              :seeds => [node1ip],
              :listen_address => node1ip,
              :rpc_address => node1ip,
              :opscenter => {
                  :interface => '0.0.0.0',
                  :stomp_interface => node1ip
              }
           },
           :java => {
             :oracle => {
                :accept_oracle_download_terms => true
              },
             :install_flavor => 'oracle',
             :jdk_version => '7'
           },
           :ntp => {
             :servers => ['0.pool.ntp.org', '1.pool.ntp.org', '2.pool.ntp.org', '3.pool.ntp.org', '4.pool.ntp.org']
           }
          }
      
      chef.run_list = ["cassandra::jna", "cassandra::datastax", "cassandra::opscenter", "cassandra::datastax-agent", "ntp"]
   end
  end
 
  config.vm.define "cassandra-node-2" do |configNode|
    configNode.vm.hostname = "cassandra-node-2"
    configNode.vm.box = "centos64-x64"
    configNode.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box" 
    configNode.vm.network 'private_network', ip: node2ip
    
    configNode.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    configNode.vm.provision :chef_solo do |chef|
         chef.log_level = :debug
         chef.json = {
           :cassandra => {
              :repository_username => '<enter username>',
              :repository_password => '<enter password>',
              :cluster_name => 'SoundFingerprinting Cluster',
              :initial_token => '-3074457345618258603',
              :seeds => [node1ip],
              :listen_address => node2ip,
              :rpc_address => node2ip,
              :opscenter => {
                  :stomp_interface => node1ip
              }
           },
           :java => {
             :oracle => {
                :accept_oracle_download_terms => true
             },
             :install_flavor => 'oracle',
             :jdk_version => '7'
           },
           :ntp => {
             :servers => ['0.pool.ntp.org', '1.pool.ntp.org', '2.pool.ntp.org', '3.pool.ntp.org', '4.pool.ntp.org']
           }
          }

      chef.run_list = ["cassandra::jna","cassandra::datastax", "cassandra::datastax-agent", "ntp"]
   end
  end

  #configure HADOOP node
  config.vm.define "cassandra-node-3" do |configNode|
    configNode.vm.hostname = "cassandra-node-3"
    configNode.vm.box = "centos64-x64"
    configNode.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box" 
    configNode.vm.network 'private_network', ip: node3ip
    
    configNode.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    configNode.vm.provision :chef_solo do |chef|
         chef.log_level = :debug
         chef.json = {
           :cassandra => {
              :repository_username => '<enter username>',
              :repository_password => '<enter password>',
              :cluster_name => 'SoundFingerprinting Cluster',
              :initial_token => '3074457345618258602',
              :seeds => [node1ip],
              :listen_address => node3ip,
              :rpc_address => node3ip,
              :analitical_node => '1',
              :vnodes => '1',
              :opscenter => {
                  :stomp_interface => node1ip
              }
           },
           :java => {
             :oracle => {
                :accept_oracle_download_terms => true
             },
             :install_flavor => 'oracle',
             :jdk_version => '7'
           },
           :ntp => {
             :servers => ['0.pool.ntp.org', '1.pool.ntp.org', '2.pool.ntp.org', '3.pool.ntp.org', '4.pool.ntp.org']
           }
          }

      chef.run_list = ["cassandra::jna", "cassandra::datastax", "cassandra::datastax-agent", "ntp"]
   end
  end
end
