namespace SoundFingerprinting.Configuration
{
    using System;
    using SoundFingerprinting.Command;
    using SoundFingerprinting.Configuration.Frames;
    using SoundFingerprinting.Data;
    using SoundFingerprinting.Strides;

    /// <summary>
    ///  Fingerprint configuration class used to define the configuration parameters used to create fingerprints.
    /// </summary>
    public abstract class FingerprintConfiguration
    {
        /// <summary>
        ///  Gets or sets stride between two consecutive fingerprints.
        /// </summary>
        /// <remarks>
        ///   The smaller the stride, the better the recognition rate, as more fingerprints are generated per one second of audio. <br />
        ///   Default value <see cref="IncrementalStaticStride"/> with 512 samples stride. <br/>
        ///   Ignored by video fingerprinting algorithm.
        /// </remarks>
        public IStride Stride
        {
            get => SpectrogramConfig.Stride;
            set => SpectrogramConfig.Stride = value;
        }

        /// <summary>
        ///   Gets or sets Haar Wavelet norm. The default value is Math.Sqrt(2).
        /// </summary>
        public double HaarWaveletNorm { get; set; }

        /// <summary>
        ///  Gets or sets frequency range to analyze when creating the fingerprints.
        /// </summary>
        /// <exception cref="ArgumentException"><see cref="SoundFingerprinting.Configuration.FrequencyRange.Max"/> has to be less than <see cref="SampleRate"/> divided by 2 to satisfy <a href="https://en.wikipedia.org/wiki/Nyquist_frequency">Nyquist frequency</a>.</exception>
        /// <remarks>
        ///  Default: [318-2000], since it worked well for <a href="http://ismir2002.ircam.fr/proceedings/02-FP04-2.pdf">others</a>. <br />
        ///  Setting Min below 300Hz does not make a lot of sense since you will start picking up low frequencies which are normally regarded as noise (i.e., airplane noise). <br/>
        ///  Setting Max above 2,000Hz makes sense if the audio which you are fingerprinting contains a lot of unique harmonics (i.e., classical music). <br />
        ///  Measured in hertz. Ignored by video fingerprinting.
        /// </remarks>
        public FrequencyRange FrequencyRange
        {
            get => SpectrogramConfig.FrequencyRange;
            set
            {
                if (value.Max > SampleRate / 2)
                {
                    throw new ArgumentException($"Max frequency can't exceed Nyquist frequency {SampleRate / 2}", nameof(FrequencyRange.Max));
                }
                
                SpectrogramConfig.FrequencyRange = value;
            }
        }

        /// <summary>
        ///  Gets or sets spectrogram creation configuration parameters.
        /// </summary>
        internal SpectrogramConfig SpectrogramConfig { get; set; } = null!;

        /// <summary>
        ///   Gets number of audio samples read for one fingerprint.
        /// </summary>
        internal int SamplesPerFingerprint => SpectrogramConfig.ImageLength * SpectrogramConfig.Overlap;

        /// <summary>
        ///  Gets or sets number of top wavelets to keep after wavelet transformation.
        /// </summary>
        /// <remarks>
        ///   Each fingerprint is generated by min-hashing an image transformed through standard wavelet decomposition.
        ///   The size of the resulting image is 128 * 32 pixels. <br/>
        ///   In layman's terms, <see cref="TopWavelets"/> define how many of those pixels (sorted by magnitude) have to be taken into account by the Min-Hash algorithm to hash the image.
        ///   Audio default = 200, which is ~4.9%, Video default = 4%.
        ///   Lowering this value will instruct the algorithm to consider fewer top wavelets, potentially making it more robust to degraded audio or noisy video.
        ///   The same number of top wavelets have to be used by both <see cref="FingerprintCommand"/> and <see cref="QueryCommand"/>.
        /// </remarks>
        public int TopWavelets { get; set; }

        /// <summary>
        ///   Gets or sets sample rate used during generation of acoustic fingerprints.
        /// </summary>
        /// <remarks>
        ///  Sample rate to down sample the input audio, before extracting log-spectrum of a specific <see cref="FrequencyRange"/>. <br/>
        ///  Ignored by video fingerprinting.
        /// </remarks>
        public int SampleRate { get; set; }

        /// <summary>
        ///  Gets or sets hashing configuration parameters.
        /// </summary>
        public HashingConfig HashingConfig { get; set; } = null!;

        /// <summary>
        ///  Gets fingerprint length in seconds.
        /// </summary>
        public virtual double FingerprintLengthInSeconds => (double)SamplesPerFingerprint / SampleRate;

        /// <summary>
        ///  Gets or sets the transformation for the original point that needs to be saved for second level cross-check.
        /// </summary>
        public Func<Frame, byte[]> OriginalPointSaveTransform { get; set; } = null!;

        /// <summary>
        ///  Gets or sets frame normalization applied before generating fingerprints.
        /// </summary>
        /// <remarks>
        ///  Frame normalization allows to apply
        /// </remarks>
        public IFrameNormalization FrameNormalizationTransform { get; set; } = null!;

        /// <summary>
        ///  Gets or sets a value indicating whether to capture a per-second spectral profile (SFM + power)
        ///  alongside the fingerprints and attach it to the resulting <c>Hashes.Properties</c>.
        /// </summary>
        /// <remarks>
        ///  When <c>true</c>, the per-Frame SFM and power are computed from the raw spectrum before <see cref="LogSpectrumNormalization"/> mutates the values, bucketed into one-second windows,
        ///  encoded via <see cref="SoundFingerprinting.Audio.SpectralProfileCodecV1"/>, and stored on <c>Hashes.Properties[SpectralProfileKeys.SpectralProfile]</c> as a base64 string.
        ///  Default value is <c>false</c>. Setting <see cref="QueryConfiguration.SfmMatchStrategy"/> to a non-no-op strategy flips this on for queries via the setter cascade.
        ///  <para>
        ///   <b>Audio only.</b> SFM and power are spectrum-domain concepts and have no meaningful interpretation for video frames (pixel intensities).
        ///   The video fingerprinting path silently ignores this flag — no profile is attached to video <c>Hashes</c> regardless of the value here.
        ///  </para>
        ///  <para>
        ///   <b>Performance.</b> The cost is dominated by pass 1 of <see cref="SoundFingerprinting.Audio.SpectralProfileService"/>:
        ///   for each Frame, <c>O(rows × cols)</c> work with one <c>Math.Log</c> per spectrum bin (default 128 × 32 ≈ 4k log ops per Frame), then a per-row median via quickselect
        ///   (<c>O(rows)</c> average, not a full sort). Pass 2 (bucket → fold means → encode) is <c>O(frames + seconds)</c> and irrelevant to the budget.
        ///  </para>
        ///  <para>
        ///   <b>Memory.</b> The input frames enumerable is materialised once if not already a list. Each Frame holds a ~16 KB float array at the default 128 × 32 layout — peak ~12 MB for a 30 s ad,
        ///   ~1.4 GB for a 1-hour stream. Per-worker overhead is a small <c>double[rows]</c> buffer (~1 KB at default rows). Chunk long-form content if memory is constrained.
        ///  </para>
        /// </remarks>
        public bool ComputeSpectralProfile { get; set; }
    }
}