name             'sfcookbook'
maintainer       'Ciumac Sergiu'
maintainer_email 'ciumac.sergiu@gmail.com'
license          'All rights reserved'
description      'SoundFingerprinting cookbook'
long_description 'Installs and initilizes Datastax Cassandra cluster for SoundFingerprinting project'
version          '0.1.0'

depends          'ntp'
depends          'chef-solo-search'
depends          'cassandra'
