# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

#tokens are generated using the following strategy
#python -c 'print [str(((2**64 / number_of_tokens) * i) - 2**63) for i in range(number_of_tokens)]'

node1ip = '10.11.12.13'

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  config.vm.define "cassandra-node-1" do |configNode|
    configNode.vm.hostname = "cassandra-node-1"
    configNode.vm.box = "centos64-x64"
    configNode.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box" 
    
    configNode.vm.network :private_network, type: "dhcp" 
    
    configNode.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
 

    configNode.vm.provision :chef_solo do |chef|
         chef.log_level = :debug
         chef.json = {
           :cassandra => {
              :cluster_name => 'Sound Fingerprinting Cluster',
              :initial_token => '-9223372036854775808'
           },
           :ntp => {
             :servers => ['0.pool.ntp.org', '1.pool.ntp.org', '2.pool.ntp.org', '3.pool.ntp.org', '4.pool.ntp.org']
           }
          }
      
      chef.run_list = ["recipe[cassandra::default]", "ntp"]
   end
  end
 
  config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true
end
